# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20161122_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='name_mae',
            new_name='nome_mae',
        ),
    ]
