# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20161123_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteendereco',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='fone_ddd',
            field=models.CharField(max_length=2, verbose_name='DDD:'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='fone_numero',
            field=models.CharField(max_length=11, verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nº casa'),
        ),
    ]
