# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20161128_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteendereco',
            name='fone_ddd',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='DDD:'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='fone_numero',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone:'),
        ),
    ]
