# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20161129_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='profissao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
