# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20161129_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteendereco',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='codigo_municipio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Codigo Municipio'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
