# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_auto_20161201_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
