# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_auto_20161201_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cartao_sus',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='SUS'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidade',
            field=models.CharField(blank=True, default='brasileira', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='fone_numero',
            field=models.CharField(max_length=11, verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='logradouro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
    ]
