# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0017_auto_20170321_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não informado')], default='N', max_length=1, verbose_name='Sexo'),
        ),
    ]
