# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0018_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteendereco',
            name='fone_numero',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
