# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0003_auto_20170403_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exame',
            options={'ordering': ['ordem_exibicao'], 'verbose_name': 'Exame do Laudo', 'verbose_name_plural': 'Exames do Laudo'},
        ),
    ]
