# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0005_auto_20170612_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoExame',
            new_name='Exame',
        ),
    ]
