# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0006_auto_20170612_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='nome',
            field=models.IntegerField(choices=[(1, 'EXAME CITOPATOLÓGICO CERVICAL UTERINO'), (2, 'Urina Rotina - Método Convencional'), (3, 'Glicose / Colesterol')], default=1),
        ),
    ]
