# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0008_auto_20170617_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameSubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exame_subitem', to='exame.Exame')),
            ],
            options={
                'verbose_name': 'Sub Item Exame',
                'verbose_name_plural': 'Sub Itens Exame',
                'ordering': ['descricao'],
            },
        ),
    ]
