# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0009_examesubitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examesubitem',
            name='exame',
        ),
        migrations.DeleteModel(
            name='ExameSubItem',
        ),
    ]
