# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0012_subexameitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subexame',
            options={'verbose_name': 'Sub Exame', 'verbose_name_plural': 'Sub Exames'},
        ),
        migrations.AlterModelOptions(
            name='subexameitem',
            options={'verbose_name': 'Sub Item dos Exame', 'verbose_name_plural': 'Sub Itens dos Exames'},
        ),
    ]
