# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convenio',
            options={'ordering': ['descricao'], 'verbose_name': 'Convenio', 'verbose_name_plural': 'Convenios'},
        ),
    ]
