# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0011_subexame'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubExameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exame_sub_exame_item', to='exame.Exame')),
                ('sub_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_exame', to='exame.SubExame')),
            ],
        ),
    ]
