# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='exames',
            field=models.ManyToManyField(to='laudo.ItemExame'),
        ),
    ]
