# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0002_laudo_exames'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='paciente_pode_ver',
            field=models.BooleanField(default=False),
        ),
    ]
