# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0003_laudo_paciente_pode_ver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laudo',
            name='exames',
        ),
    ]
