# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0004_remove_laudo_exames'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameLaudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('item_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_exame', to='laudo.ItemExame')),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudo', to='laudo.Laudo')),
            ],
        ),
    ]
