# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0007_auto_20170214_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laudo',
            name='convenio',
        ),
    ]
