# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0008_remove_laudo_convenio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examelaudo',
            options={'verbose_name': 'Exame Laudo'},
        ),
    ]
