# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0009_auto_20170309_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laudo',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Laudo', 'verbose_name_plural': 'Laudos'},
        ),
    ]
