# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0011_laudo_ultima_menstruacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='data_coleta',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da coleta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laudo',
            name='ultima_menstruacao',
            field=models.DateTimeField(verbose_name='Data ultima menstruação'),
        ),
    ]
