# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0019_assinadoreletronico_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinadoreletronico',
            name='descricao',
        ),
        migrations.AddField(
            model_name='assinadoreletronico',
            name='nome_exibir',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='assinadoreletronico',
            name='profissao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='assinadoreletronico',
            name='registro_federal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição dos regitro'),
        ),
    ]
