# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0020_auto_20170328_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinadoreletronico',
            name='foto_assinatura',
            field=models.ImageField(null=True, upload_to='', verbose_name='Assinatura'),
        ),
    ]
