# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0023_laudo_data_assinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
