# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0027_assinadoreletronico_foto_assinatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo Exame',
            },
        ),
    ]
