# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0029_delete_tipoexame'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameUrinaRotina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_urina', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ph')),
                ('leucocitos', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Leucócitos')),
                ('hemacias', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Hemácias')),
                ('cilindros', models.CharField(max_length=100)),
                ('cristais', models.CharField(max_length=100)),
                ('parasitas', models.CharField(max_length=100)),
                ('observacao', models.TextField(verbose_name='Observação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudo_urina_rotina', to='laudo.Laudo')),
            ],
            options={
                'verbose_name': 'Exame Urina Rotina',
                'verbose_name_plural': 'Exames Urina Rotina',
            },
        ),
    ]
