# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0032_auto_20170615_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exameurinarotina',
            name='cilindros',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exameurinarotina',
            name='cristais',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exameurinarotina',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='exameurinarotina',
            name='parasitas',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
