# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0032_auto_20170615_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='data_coleta',
            field=models.DateTimeField(null=True, verbose_name='Data da coleta'),
        ),
    ]
