# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0033_auto_20170809_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='data_coleta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da coleta'),
        ),
    ]
