# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone:'),
        ),
    ]
