# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('paciente', '0017_auto_20170321_2023'),
        ('core', '0002_auto_20161208_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convenio',
        ),
    ]
