# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0010_auto_20170309_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='ultima_menstruacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
