# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0012_auto_20170316_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemexame',
            name='exame',
        ),
        migrations.AlterField(
            model_name='examelaudo',
            name='item_exame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_exame', to='exame.ItemExame'),
        ),
        migrations.DeleteModel(
            name='Exame',
        ),
        migrations.DeleteModel(
            name='ItemExame',
        ),
    ]
