# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0013_auto_20170321_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinadorEletronico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Assinadores',
                'verbose_name': 'Assinador',
            },
        ),
        migrations.AddField(
            model_name='laudo',
            name='assinado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laudo',
            name='assinado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinador', to='laudo.AssinadorEletronico'),
        ),
    ]
