# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0015_auto_20170321_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinadoreletronico',
            name='nome',
        ),
    ]
