# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0018_auto_20170327_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinadoreletronico',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição'),
        ),
    ]
