# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0030_exameurinarotina'),
    ]

    operations = [
        migrations.AddField(
            model_name='exameurinarotina',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
