# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0031_exameurinarotina_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exameurinarotina',
            name='cilindros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exameurinarotina',
            name='cristais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exameurinarotina',
            name='hemacias',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Hemácias'),
        ),
        migrations.AlterField(
            model_name='exameurinarotina',
            name='leucocitos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Leucócitos'),
        ),
        migrations.AlterField(
            model_name='exameurinarotina',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='exameurinarotina',
            name='parasitas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exameurinarotina',
            name='ph_urina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Ph'),
        ),
    ]
