# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0034_auto_20170809_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.Medico'),
        ),
    ]
