# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_paciente_profissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='raca',
            field=models.CharField(choices=[('BRA', 'Branca'), ('PRE', 'Preta'), ('PAR', 'Parda'), ('AMA', 'Amarela'), ('IND', 'Indigena / Etinia'), ('OUT', 'Outra')], default='BRA', max_length=3, verbose_name='Raça'),
        ),
    ]
