# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_auto_20161130_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteendereco',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='fone_ddd',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='DDD:'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='fone_numero',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='logradouro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='numero_casa',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Nº casa'),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='ponto_de_referencia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pacienteendereco',
            name='uf',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='UF'),
        ),
    ]
