# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_paciente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.AddField(
            model_name='pacienteendereco',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
