# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_auto_20161201_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteendereco',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
