# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161208_2111'),
        ('paciente', '0014_paciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Convenio'),
        ),
    ]
