# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0015_paciente_convenio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='sexo',
        ),
    ]
